spring.application.name=paf_project
spring.config.import=optional:file:env.properties

# Cloud PostgreSQL Database Config (Neon)
spring.datasource.url=jdbc:postgresql://ep-ancient-bread-a10l45fg-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_QcnS5uL0seYq
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Config 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Google OAuth2 Config 
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email